# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fastai_recipe": "01_custom_receipe.ipynb",
         "create_folders": "01_custom_receipe.ipynb",
         "load_fastai_model": "01_custom_receipe.ipynb",
         "save_base64_image": "01_custom_receipe.ipynb",
         "score_stream": "01_custom_receipe.ipynb",
         "create_logger": "02_capture_camera.ipynb",
         "create_folder": "02_capture_camera.ipynb",
         "capture": "02_capture_camera.ipynb"}

modules = ["custom_recipe.py",
           "capture_camera.py"]

doc_url = "https://submitCode.github.io/PooDetector/"

git_url = "https://github.com/submitCode/PooDetector/tree/master/"

def custom_doc_links(name): return None