# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_preview_folder.ipynb (unless otherwise specified).

__all__ = ['convert_path_timestamp']

# Cell
import os
import shutil
from datetime import datetime
from pathlib import Path
import pandas as pd

# Cell
def convert_path_timestamp(path:[str,Path]):
    """converts a filename to timestamp"""
    path = Path(path)
    if path.is_file() is False:
        return None

    filename = path.stem
    return datetime.strptime(filename[:14], '%Y%m%d%H%M%S')